In [147]:
import torch
print(torch.__version__)

2.10.0+cpu


In [148]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


**Creating a** **Tensor**

In [149]:
# using empty
a = torch.empty(2,3)

In [150]:
# check type
type(a)

torch.Tensor

In [151]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [152]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [153]:
# using rand
torch.rand(2,3)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [154]:
# use of seed
torch.rand(2,3)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [155]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [156]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [157]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [158]:
# other ways

# arrange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3,3), 5))


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensor Shapes**

In [159]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [160]:
x.shape

torch.Size([2, 3])

In [161]:
torch.empty_like(x)

tensor([[              0,               0,               0],
        [             65,       362789008, 135124068457744]])

In [162]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [163]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [164]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

**Tensor Data Types**

In [165]:
# find data type
x.dtype

torch.int64

In [166]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [167]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [168]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Mathematical operations**

1. Scalar operation

In [169]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [170]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2


tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

2. Element wise operation

In [171]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [172]:
# add
a + b
# sub
a - b
# multiply
a * b
# divion
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [173]:
c = torch.tensor([1, -2, 3, -4])

In [174]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [175]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [176]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [177]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [178]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [179]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [180]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction Opration

In [181]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [182]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [183]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [184]:
# median
torch.median(e)

tensor(0.)

In [185]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [186]:
# product
torch.prod(e)

tensor(0.)

In [187]:
# standard devision
torch.std(e)

tensor(4.4272)

In [188]:
# variance
torch.var(e)

tensor(19.6000)

In [189]:
# argmax
torch.argmax(e)

tensor(5)

In [190]:
# argmin
torch.argmin(e)

tensor(1)

4. Matrix operations

In [191]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [192]:
# matrix multiplication
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [193]:
# dot product
# torch.dot(vector1, vector2)

In [194]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [195]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [196]:
# determinent
torch.det(h)

tensor(-110.)

In [197]:
# incerse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

5. Comparison operations

In [198]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print (i)
print (j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [199]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i |= j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[False, False, False],
        [False, False, False]])

6. Special functions

In [200]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [201]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [202]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [203]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [204]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [205]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [206]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [207]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

**Inplace Operations**

In [208]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [210]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [211]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [212]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [213]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [214]:
m.relu_() # Implace

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [215]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [216]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

**Copying a Tensor**

In [217]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [218]:
b = a

In [219]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [220]:
a[0][0] = 0

In [221]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [222]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [223]:
id(a)

135122992905056

In [224]:
id(b)

135122992905056

In [225]:
b = a.clone()

In [226]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [227]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [228]:
a[0][0] = 10

In [229]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [230]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [231]:
id(a)

135122992905056

In [232]:
id(b)

135122992320816

**Tensor Operations on GPU**

In [233]:
torch.cuda.is_available()

False

In [234]:
device = torch.device('cuda')

In [237]:
# creating a new tensor on GPU
# torch.rand(2,3), device=device

In [238]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [242]:
# b = a.to(device)

In [243]:
b + 5

tensor([[5.0000, 5.2324, 5.9141],
        [5.7668, 5.1659, 5.4393]])

In [248]:
import torch
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all the GPU operation to complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 29.7622 seconds


AssertionError: Torch not compiled with CUDA enabled

**Reshaping Tensors**

In [249]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [252]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [251]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [250]:
b = torch.rand(2,3,4)
b

tensor([[[0.1465, 0.7036, 0.8185, 0.6261],
         [0.2405, 0.5844, 0.7472, 0.9544],
         [0.1489, 0.2289, 0.0111, 0.4039]],

        [[0.9874, 0.2652, 0.6387, 0.6203],
         [0.8795, 0.2605, 0.4782, 0.8546],
         [0.3973, 0.7233, 0.5476, 0.8979]]])

In [253]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [254]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [256]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

**NumPy and PyTorch**

In [264]:
import numpy as np

In [265]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [268]:
b = a.numpy()

In [269]:
b

array([1, 2, 3])

In [270]:
type(b)

numpy.ndarray

In [271]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [272]:
torch.from_numpy(c)

tensor([1, 2, 3])